import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
// import "../../app/globals.css";
import AppSidebar from '@/components/DashboardComponent/AppSidebar';
import DashNavbar from '@/components/DashboardComponent/DashNavbar';
import { SidebarProvider } from '@/components/ui/sidebar';
import { cookies } from 'next/headers';
import Footer from '@/components/DashboardComponent/Footer';
import { Toaster } from 'sonner';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get('sidebar_state')?.value === 'true';


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}>
        <SidebarProvider defaultOpen={defaultOpen}>
          {/* <div className=""> */}
          <AppSidebar />
          {/* </div> */}
          <main className=" w-full">
            <DashNavbar />
            <div className="md:px-4">
              {children}
              <Toaster richColors position="top-right" />
            </div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
