import type { Metadata } from "next";
import "./globals.css";
import AppSidebar from "@/components/AppSidebar";
import Navabar from "@/components/DashboardNav/Navabar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased grid grid-cols-1 lg:grid-cols-12`}
      >
        <div className="col-span-2 border-2 border-amber-300">
          <AppSidebar />
        </div>

        <main className="col-span-10 border-2 border-amber-800">
          <Navabar />
          <div className="px-4">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
