import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionProviderWrapper from "@/Providers/SessionProviderWrapper";
import HomeNavbar from "./components/SharedRoutes/HomeNavbar";
import HomeFooter from "./components/SharedRoutes/HomeFooter";
import LayoutWrapper from "@/Providers/LayoutWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <SessionProviderWrapper> */}
        <nav>
          {/* <HomeNavbar /> */}
        </nav>
        <LayoutWrapper>
          {/* <main> */}
          {children}
          {/* </main> */}
        </LayoutWrapper>
        <footer>
          {/* <HomeFooter /> */}
        </footer>
        {/* </SessionProviderWrapper> */}
      </body>
    </html>
  );
}
