import { all_store_columns, StoresDataType } from '@/components/TableHelper/all_store_columns'
import { DataTable } from '@/components/TableHelper/data-table'
import { Input } from '@/components/ui/input'
import React from 'react'




const getData = async (): Promise<StoresDataType[]> => {
  return [
    {
      serial: '1',
      store_logo: 'https://static.vecteezy.com/system/resources/previews/019/166/318/non_2x/lion-head-lion-logo-symbol-gaming-logo-elegant-element-for-brand-abstract-symbols-vector.jpg',
      store_name: 'Shannon-Knight',
      business_name: 'Shannon-Knight LLC',
      total_product: 120,
      total_earnings: 5000,
      current_balance: 2000,
      commission: 5,
      status: 'pending',
      created_at: '2024-09-03',
    },
    {
      serial: '2',
      store_logo: 'https://static.vecteezy.com/system/resources/previews/019/166/318/non_2x/lion-head-lion-logo-symbol-gaming-logo-elegant-element-for-brand-abstract-symbols-vector.jpg',
      store_name: 'Meyer LLC',
      business_name: 'Meyer LLC',
      total_product: 85,
      total_earnings: 3000,
      current_balance: 1200,
      commission: 7,
      status: 'active',
      created_at: '2024-01-08',
    },
    {
      serial: '3',
      store_logo: 'https://static.vecteezy.com/system/resources/previews/019/166/318/non_2x/lion-head-lion-logo-symbol-gaming-logo-elegant-element-for-brand-abstract-symbols-vector.jpg',
      store_name: 'Thompson-Cruz',
      business_name: 'Thompson-Cruz Ltd.',
      total_product: 45,
      total_earnings: 1500,
      current_balance: 500,
      commission: 6,
      status: 'pending',
      created_at: '2024-10-03',
    },
    {
      serial: '4',
      store_logo: 'https://static.vecteezy.com/system/resources/previews/019/166/318/non_2x/lion-head-lion-logo-symbol-gaming-logo-elegant-element-for-brand-abstract-symbols-vector.jpg',
      store_name: 'Frank, Zavala and Williams',
      business_name: 'Frank PLC',
      total_product: 200,
      total_earnings: 12000,
      current_balance: 8000,
      commission: 4,
      status: 'inactive',
      created_at: '2024-12-27',
    },
    {
      serial: '5',
      store_logo: 'https://static.vecteezy.com/system/resources/previews/019/166/318/non_2x/lion-head-lion-logo-symbol-gaming-logo-elegant-element-for-brand-abstract-symbols-vector.jpg',
      store_name: 'Fuentes PLC',
      business_name: 'Fuentes PLC',
      total_product: 70,
      total_earnings: 4000,
      current_balance: 2000,
      commission: 5,
      status: 'pending',
      created_at: '2025-04-05',
    },
    {
      serial: '6',
      store_logo: 'https://static.vecteezy.com/system/resources/previews/019/166/318/non_2x/lion-head-lion-logo-symbol-gaming-logo-elegant-element-for-brand-abstract-symbols-vector.jpg',
      store_name: 'Carroll PLC',
      business_name: 'Carroll PLC',
      total_product: 95,
      total_earnings: 5500,
      current_balance: 3000,
      commission: 6,
      status: 'inactive',
      created_at: '2023-09-14',
    },
    {
      serial: '7',
      store_logo: 'https://static.vecteezy.com/system/resources/previews/019/166/318/non_2x/lion-head-lion-logo-symbol-gaming-logo-elegant-element-for-brand-abstract-symbols-vector.jpg',
      store_name: 'Mccarthy and Sons',
      business_name: 'Mccarthy & Sons',
      total_product: 110,
      total_earnings: 7000,
      current_balance: 4500,
      commission: 5,
      status: 'active',
      created_at: '2025-02-11',
    },
    {
      serial: '8',
      store_logo: 'https://static.vecteezy.com/system/resources/previews/019/166/318/non_2x/lion-head-lion-logo-symbol-gaming-logo-elegant-element-for-brand-abstract-symbols-vector.jpg',
      store_name: 'Adams and Sons',
      business_name: 'Adams & Sons',
      total_product: 130,
      total_earnings: 8000,
      current_balance: 5000,
      commission: 7,
      status: 'active',
      created_at: '2024-11-08',
    },
    {
      serial: '9',
      store_logo: 'https://static.vecteezy.com/system/resources/previews/019/166/318/non_2x/lion-head-lion-logo-symbol-gaming-logo-elegant-element-for-brand-abstract-symbols-vector.jpg',
      store_name: 'Reynolds-Wilson',
      business_name: 'Reynolds-Wilson Ltd.',
      total_product: 60,
      total_earnings: 3500,
      current_balance: 1800,
      commission: 6,
      status: 'active',
      created_at: '2023-09-23',
    },
    {
      serial: '10',
      store_logo: 'https://static.vecteezy.com/system/resources/previews/019/166/318/non_2x/lion-head-lion-logo-symbol-gaming-logo-elegant-element-for-brand-abstract-symbols-vector.jpg',
      store_name: 'Petty, Garcia and Hurst',
      business_name: 'Petty PLC',
      total_product: 80,
      total_earnings: 4200,
      current_balance: 2000,
      commission: 5,
      status: 'inactive',
      created_at: '2024-06-25',
    },
    {
      serial: '11',
      store_logo: 'https://static.vecteezy.com/system/resources/previews/019/166/318/non_2x/lion-head-lion-logo-symbol-gaming-logo-elegant-element-for-brand-abstract-symbols-vector.jpg',
      store_name: 'Rivas-Ortiz',
      business_name: 'Rivas-Ortiz Ltd.',
      total_product: 90,
      total_earnings: 5000,
      current_balance: 2500,
      commission: 6,
      status: 'inactive',
      created_at: '2025-03-10',
    },
    {
      serial: '12',
      store_logo: 'https://static.vecteezy.com/system/resources/previews/019/166/318/non_2x/lion-head-lion-logo-symbol-gaming-logo-elegant-element-for-brand-abstract-symbols-vector.jpg',
      store_name: 'Everett-Smith',
      business_name: 'Everett-Smith LLC',
      total_product: 75,
      total_earnings: 3900,
      current_balance: 1500,
      commission: 5,
      status: 'pending',
      created_at: '2025-02-10',
    },
    {
      serial: '13',
      store_logo: 'https://static.vecteezy.com/system/resources/previews/019/166/318/non_2x/lion-head-lion-logo-symbol-gaming-logo-elegant-element-for-brand-abstract-symbols-vector.jpg',
      store_name: 'Wright, Jones and Valentine',
      business_name: 'Wright Group',
      total_product: 65,
      total_earnings: 3200,
      current_balance: 1200,
      commission: 5,
      status: 'pending',
      created_at: '2024-10-23',
    },
    {
      serial: '14',
      store_logo: 'https://static.vecteezy.com/system/resources/previews/019/166/318/non_2x/lion-head-lion-logo-symbol-gaming-logo-elegant-element-for-brand-abstract-symbols-vector.jpg',
      store_name: 'Owens-Hoffman',
      business_name: 'Owens-Hoffman Ltd.',
      total_product: 140,
      total_earnings: 9000,
      current_balance: 6000,
      commission: 6,
      status: 'active',
      created_at: '2024-06-28',
    },
    {
      serial: '15',
      store_logo: 'https://static.vecteezy.com/system/resources/previews/019/166/318/non_2x/lion-head-lion-logo-symbol-gaming-logo-elegant-element-for-brand-abstract-symbols-vector.jpg',
      store_name: 'Guerrero, Obrien and Atkinson',
      business_name: 'Guerrero LLC',
      total_product: 100,
      total_earnings: 6500,
      current_balance: 3500,
      commission: 5,
      status: 'active',
      created_at: '2025-06-01',
    },
    {
      serial: '16',
      store_logo: 'https://static.vecteezy.com/system/resources/previews/019/166/318/non_2x/lion-head-lion-logo-symbol-gaming-logo-elegant-element-for-brand-abstract-symbols-vector.jpg',
      store_name: 'Leblanc LLC',
      business_name: 'Leblanc LLC',
      total_product: 55,
      total_earnings: 2800,
      current_balance: 900,
      commission: 4,
      status: 'pending',
      created_at: '2024-01-01',
    },
    {
      serial: '17',
      store_logo: 'https://static.vecteezy.com/system/resources/previews/019/166/318/non_2x/lion-head-lion-logo-symbol-gaming-logo-elegant-element-for-brand-abstract-symbols-vector.jpg',
      store_name: 'Miller Group',
      business_name: 'Miller Group',
      total_product: 45,
      total_earnings: 2000,
      current_balance: 600,
      commission: 5,
      status: 'pending',
      created_at: '2023-12-29',
    },
    {
      serial: '18',
      store_logo: 'https://static.vecteezy.com/system/resources/previews/019/166/318/non_2x/lion-head-lion-logo-symbol-gaming-logo-elegant-element-for-brand-abstract-symbols-vector.jpg',
      store_name: 'Shea, Jenkins and Moore',
      business_name: 'Shea PLC',
      total_product: 70,
      total_earnings: 4000,
      current_balance: 1500,
      commission: 6,
      status: 'inactive',
      created_at: '2023-11-13',
    },
    {
      serial: '19',
      store_logo: 'https://static.vecteezy.com/system/resources/previews/019/166/318/non_2x/lion-head-lion-logo-symbol-gaming-logo-elegant-element-for-brand-abstract-symbols-vector.jpg',
      store_name: 'Turner-Harris',
      business_name: 'Turner-Harris Ltd.',
      total_product: 120,
      total_earnings: 7500,
      current_balance: 4000,
      commission: 5,
      status: 'active',
      created_at: '2024-02-22',
    },
    {
      serial: '20',
      store_logo: 'https://static.vecteezy.com/system/resources/previews/019/166/318/non_2x/lion-head-lion-logo-symbol-gaming-logo-elegant-element-for-brand-abstract-symbols-vector.jpg',
      store_name: 'Rosales-Dominguez',
      business_name: 'Rosales-Dominguez LLC',
      total_product: 90,
      total_earnings: 5000,
      current_balance: 2500,
      commission: 6,
      status: 'active',
      created_at: '2023-09-17',
    },
    {
      serial: '21',
      store_logo: 'https://static.vecteezy.com/system/resources/previews/019/166/318/non_2x/lion-head-lion-logo-symbol-gaming-logo-elegant-element-for-brand-abstract-symbols-vector.jpg',
      store_name: 'Sanders-Myers',
      business_name: 'Sanders LLC',
      total_product: 60,
      total_earnings: 3000,
      current_balance: 1200,
      commission: 5,
      status: 'active',
      created_at: '2025-01-02',
    },
    {
      serial: '22',
      store_logo: 'https://static.vecteezy.com/system/resources/previews/019/166/318/non_2x/lion-head-lion-logo-symbol-gaming-logo-elegant-element-for-brand-abstract-symbols-vector.jpg',
      store_name: 'Tran PLC',
      business_name: 'Tran PLC',
      total_product: 40,
      total_earnings: 2000,
      current_balance: 800,
      commission: 4,
      status: 'inactive',
      created_at: '2023-11-28',
    },
    {
      serial: '23',
      store_logo: 'https://static.vecteezy.com/system/resources/previews/019/166/318/non_2x/lion-head-lion-logo-symbol-gaming-logo-elegant-element-for-brand-abstract-symbols-vector.jpg',
      store_name: 'Padilla Group',
      business_name: 'Padilla LLC',
      total_product: 85,
      total_earnings: 4200,
      current_balance: 2000,
      commission: 5,
      status: 'inactive',
      created_at: '2025-07-07',
    }
  ]

}

export default async function ViewAllStores() {
  const data = await getData();
  return (
    <div className="m-5 p-5 border ">
      <div >
        <h1 className="text-lg font-semibold border-l-2 border-blue-500">
          <span className="pl-5">Store List</span>
        </h1>
      </div>
      <div className="md:flex justify-between my-5 space-y-2.5">
        <p>Show (Pagination) entries</p>
        <span className="md:flex gap-4 space-y-2.5">
          <span className="flex items-center gap-2">
            Search:
            <Input type="text" className="border border-gray-500" />
          </span>
        </span>
      </div>
      <DataTable columns={all_store_columns} data={data} />
    </div>
  )
}
